# Generated by Django 5.0.1 on 2024-03-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_photo_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_photo',
            old_name='staff',
            new_name='user',
        ),
    ]
