# Generated by Django 5.0.1 on 2024-03-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_photo',
            name='phone',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
