# Generated by Django 5.0.1 on 2024-03-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_staff_profile_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_photo',
            name='image',
            field=models.ImageField(default='download.jpg', null=True, upload_to='profile_images'),
        ),
    ]
