# Generated by Django 5.0.3 on 2024-03-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('P_Type', models.CharField(max_length=20)),
                ('p_Name', models.CharField(max_length=15)),
                ('P_Brand', models.CharField(max_length=10)),
                ('P_Stock', models.IntegerField()),
                ('R_date', models.DateField(blank=True, null=True)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
