# Generated by Django 5.0.3 on 2024-03-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='P_Size',
            field=models.IntegerField(default=8),
        ),
    ]
