# Generated by Django 5.0.3 on 2024-03-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_p_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='PS_Size',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='P_Size',
            field=models.IntegerField(),
        ),
    ]
